FROM python:3.12-bookworm
WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apt update
RUN apt install -y gfortran
RUN apt install -y libhdf5-dev
RUN apt install -y libgl-dev
RUN pip install --no-cache-dir -r requirements.txt
ENV PATH="/opt/gtk/bin:$PATH"
COPY . .

CMD [ "python", "-m", "MTE" ]
# CMD ["python", "./debug.py" ]